package android.support.design;

import mobi.mmdt.componentsutils.C1117d;

/* renamed from: android.support.design.k */
public final class C0070k {
    public static final int[] ActionBar;
    public static final int[] ActionBarLayout;
    public static final int ActionBarLayout_android_layout_gravity = 0;
    public static final int ActionBar_background = 10;
    public static final int ActionBar_backgroundSplit = 12;
    public static final int ActionBar_backgroundStacked = 11;
    public static final int ActionBar_contentInsetEnd = 21;
    public static final int ActionBar_contentInsetLeft = 22;
    public static final int ActionBar_contentInsetRight = 23;
    public static final int ActionBar_contentInsetStart = 20;
    public static final int ActionBar_customNavigationLayout = 13;
    public static final int ActionBar_displayOptions = 3;
    public static final int ActionBar_divider = 9;
    public static final int ActionBar_elevation = 24;
    public static final int ActionBar_height = 0;
    public static final int ActionBar_hideOnContentScroll = 19;
    public static final int ActionBar_homeAsUpIndicator = 26;
    public static final int ActionBar_homeLayout = 14;
    public static final int ActionBar_icon = 7;
    public static final int ActionBar_indeterminateProgressStyle = 16;
    public static final int ActionBar_itemPadding = 18;
    public static final int ActionBar_logo = 8;
    public static final int ActionBar_navigationMode = 2;
    public static final int ActionBar_popupTheme = 25;
    public static final int ActionBar_progressBarPadding = 17;
    public static final int ActionBar_progressBarStyle = 15;
    public static final int ActionBar_subtitle = 4;
    public static final int ActionBar_subtitleTextStyle = 6;
    public static final int ActionBar_title = 1;
    public static final int ActionBar_titleTextStyle = 5;
    public static final int[] ActionMenuItemView;
    public static final int ActionMenuItemView_android_minWidth = 0;
    public static final int[] ActionMenuView;
    public static final int[] ActionMode;
    public static final int ActionMode_background = 3;
    public static final int ActionMode_backgroundSplit = 4;
    public static final int ActionMode_closeItemLayout = 5;
    public static final int ActionMode_height = 0;
    public static final int ActionMode_subtitleTextStyle = 2;
    public static final int ActionMode_titleTextStyle = 1;
    public static final int[] ActivityChooserView;
    public static final int ActivityChooserView_expandActivityOverflowButtonDrawable = 1;
    public static final int ActivityChooserView_initialActivityCount = 0;
    public static final int[] AlertDialog;
    public static final int AlertDialog_android_layout = 0;
    public static final int AlertDialog_buttonPanelSideLayout = 1;
    public static final int AlertDialog_listItemLayout = 5;
    public static final int AlertDialog_listLayout = 2;
    public static final int AlertDialog_multiChoiceItemLayout = 3;
    public static final int AlertDialog_singleChoiceItemLayout = 4;
    public static final int[] AppBarLayout;
    public static final int[] AppBarLayout_LayoutParams;
    public static final int AppBarLayout_LayoutParams_layout_scrollFlags = 0;
    public static final int AppBarLayout_LayoutParams_layout_scrollInterpolator = 1;
    public static final int AppBarLayout_android_background = 0;
    public static final int AppBarLayout_elevation = 1;
    public static final int AppBarLayout_expanded = 2;
    public static final int[] AppCompatTextView;
    public static final int AppCompatTextView_android_textAppearance = 0;
    public static final int AppCompatTextView_textAllCaps = 1;
    public static final int[] ButtonBarLayout;
    public static final int ButtonBarLayout_allowStacking = 0;
    public static final int[] CollapsingAppBarLayout_LayoutParams;
    public static final int CollapsingAppBarLayout_LayoutParams_layout_collapseMode = 0;
    public static final int f264xad49a364 = 1;
    public static final int[] CollapsingToolbarLayout;
    public static final int CollapsingToolbarLayout_collapsedTitleGravity = 11;
    public static final int CollapsingToolbarLayout_collapsedTitleTextAppearance = 7;
    public static final int CollapsingToolbarLayout_contentScrim = 8;
    public static final int CollapsingToolbarLayout_expandedTitleGravity = 12;
    public static final int CollapsingToolbarLayout_expandedTitleMargin = 1;
    public static final int CollapsingToolbarLayout_expandedTitleMarginBottom = 5;
    public static final int CollapsingToolbarLayout_expandedTitleMarginEnd = 4;
    public static final int CollapsingToolbarLayout_expandedTitleMarginStart = 2;
    public static final int CollapsingToolbarLayout_expandedTitleMarginTop = 3;
    public static final int CollapsingToolbarLayout_expandedTitleTextAppearance = 6;
    public static final int CollapsingToolbarLayout_statusBarScrim = 9;
    public static final int CollapsingToolbarLayout_title = 0;
    public static final int CollapsingToolbarLayout_titleEnabled = 13;
    public static final int CollapsingToolbarLayout_toolbarId = 10;
    public static final int[] CompoundButton;
    public static final int CompoundButton_android_button = 0;
    public static final int CompoundButton_buttonTint = 1;
    public static final int CompoundButton_buttonTintMode = 2;
    public static final int[] CoordinatorLayout;
    public static final int[] CoordinatorLayout_LayoutParams;
    public static final int CoordinatorLayout_LayoutParams_android_layout_gravity = 0;
    public static final int CoordinatorLayout_LayoutParams_layout_anchor = 2;
    public static final int CoordinatorLayout_LayoutParams_layout_anchorGravity = 4;
    public static final int CoordinatorLayout_LayoutParams_layout_behavior = 1;
    public static final int CoordinatorLayout_LayoutParams_layout_keyline = 3;
    public static final int CoordinatorLayout_keylines = 0;
    public static final int CoordinatorLayout_statusBarBackground = 1;
    public static final int[] DrawerArrowToggle;
    public static final int DrawerArrowToggle_arrowHeadLength = 4;
    public static final int DrawerArrowToggle_arrowShaftLength = 5;
    public static final int DrawerArrowToggle_barLength = 6;
    public static final int DrawerArrowToggle_color = 0;
    public static final int DrawerArrowToggle_drawableSize = 2;
    public static final int DrawerArrowToggle_gapBetweenBars = 3;
    public static final int DrawerArrowToggle_spinBars = 1;
    public static final int DrawerArrowToggle_thickness = 7;
    public static final int[] FloatingActionButton;
    public static final int FloatingActionButton_backgroundTint = 5;
    public static final int FloatingActionButton_backgroundTintMode = 6;
    public static final int FloatingActionButton_borderWidth = 4;
    public static final int FloatingActionButton_elevation = 0;
    public static final int FloatingActionButton_fabSize = 2;
    public static final int FloatingActionButton_pressedTranslationZ = 3;
    public static final int FloatingActionButton_rippleColor = 1;
    public static final int[] ForegroundLinearLayout;
    public static final int ForegroundLinearLayout_android_foreground = 0;
    public static final int ForegroundLinearLayout_android_foregroundGravity = 1;
    public static final int ForegroundLinearLayout_foregroundInsidePadding = 2;
    public static final int[] LinearLayoutCompat;
    public static final int[] LinearLayoutCompat_Layout;
    public static final int LinearLayoutCompat_Layout_android_layout_gravity = 0;
    public static final int LinearLayoutCompat_Layout_android_layout_height = 2;
    public static final int LinearLayoutCompat_Layout_android_layout_weight = 3;
    public static final int LinearLayoutCompat_Layout_android_layout_width = 1;
    public static final int LinearLayoutCompat_android_baselineAligned = 2;
    public static final int LinearLayoutCompat_android_baselineAlignedChildIndex = 3;
    public static final int LinearLayoutCompat_android_gravity = 0;
    public static final int LinearLayoutCompat_android_orientation = 1;
    public static final int LinearLayoutCompat_android_weightSum = 4;
    public static final int LinearLayoutCompat_divider = 5;
    public static final int LinearLayoutCompat_dividerPadding = 8;
    public static final int LinearLayoutCompat_measureWithLargestChild = 6;
    public static final int LinearLayoutCompat_showDividers = 7;
    public static final int[] ListPopupWindow;
    public static final int ListPopupWindow_android_dropDownHorizontalOffset = 0;
    public static final int ListPopupWindow_android_dropDownVerticalOffset = 1;
    public static final int[] MenuGroup;
    public static final int MenuGroup_android_checkableBehavior = 5;
    public static final int MenuGroup_android_enabled = 0;
    public static final int MenuGroup_android_id = 1;
    public static final int MenuGroup_android_menuCategory = 3;
    public static final int MenuGroup_android_orderInCategory = 4;
    public static final int MenuGroup_android_visible = 2;
    public static final int[] MenuItem;
    public static final int MenuItem_actionLayout = 14;
    public static final int MenuItem_actionProviderClass = 16;
    public static final int MenuItem_actionViewClass = 15;
    public static final int MenuItem_android_alphabeticShortcut = 9;
    public static final int MenuItem_android_checkable = 11;
    public static final int MenuItem_android_checked = 3;
    public static final int MenuItem_android_enabled = 1;
    public static final int MenuItem_android_icon = 0;
    public static final int MenuItem_android_id = 2;
    public static final int MenuItem_android_menuCategory = 5;
    public static final int MenuItem_android_numericShortcut = 10;
    public static final int MenuItem_android_onClick = 12;
    public static final int MenuItem_android_orderInCategory = 6;
    public static final int MenuItem_android_title = 7;
    public static final int MenuItem_android_titleCondensed = 8;
    public static final int MenuItem_android_visible = 4;
    public static final int MenuItem_showAsAction = 13;
    public static final int[] MenuView;
    public static final int MenuView_android_headerBackground = 4;
    public static final int MenuView_android_horizontalDivider = 2;
    public static final int MenuView_android_itemBackground = 5;
    public static final int MenuView_android_itemIconDisabledAlpha = 6;
    public static final int MenuView_android_itemTextAppearance = 1;
    public static final int MenuView_android_verticalDivider = 3;
    public static final int MenuView_android_windowAnimationStyle = 0;
    public static final int MenuView_preserveIconSpacing = 7;
    public static final int[] NavigationView;
    public static final int NavigationView_android_background = 0;
    public static final int NavigationView_android_fitsSystemWindows = 1;
    public static final int NavigationView_android_maxWidth = 2;
    public static final int NavigationView_elevation = 3;
    public static final int NavigationView_headerLayout = 9;
    public static final int NavigationView_itemBackground = 7;
    public static final int NavigationView_itemIconTint = 5;
    public static final int NavigationView_itemTextAppearance = 8;
    public static final int NavigationView_itemTextColor = 6;
    public static final int NavigationView_menu = 4;
    public static final int[] PopupWindow;
    public static final int[] PopupWindowBackgroundState;
    public static final int PopupWindowBackgroundState_state_above_anchor = 0;
    public static final int PopupWindow_android_popupBackground = 0;
    public static final int PopupWindow_overlapAnchor = 1;
    public static final int[] RecyclerView;
    public static final int RecyclerView_android_orientation = 0;
    public static final int RecyclerView_layoutManager = 1;
    public static final int RecyclerView_reverseLayout = 3;
    public static final int RecyclerView_spanCount = 2;
    public static final int RecyclerView_stackFromEnd = 4;
    public static final int[] ScrimInsetsFrameLayout;
    public static final int ScrimInsetsFrameLayout_insetForeground = 0;
    public static final int[] ScrollingViewBehavior_Params;
    public static final int ScrollingViewBehavior_Params_behavior_overlapTop = 0;
    public static final int[] SearchView;
    public static final int SearchView_android_focusable = 0;
    public static final int SearchView_android_imeOptions = 3;
    public static final int SearchView_android_inputType = 2;
    public static final int SearchView_android_maxWidth = 1;
    public static final int SearchView_closeIcon = 8;
    public static final int SearchView_commitIcon = 13;
    public static final int SearchView_defaultQueryHint = 7;
    public static final int SearchView_goIcon = 9;
    public static final int SearchView_iconifiedByDefault = 5;
    public static final int SearchView_layout = 4;
    public static final int SearchView_queryBackground = 15;
    public static final int SearchView_queryHint = 6;
    public static final int SearchView_searchHintIcon = 11;
    public static final int SearchView_searchIcon = 10;
    public static final int SearchView_submitBackground = 16;
    public static final int SearchView_suggestionRowLayout = 14;
    public static final int SearchView_voiceIcon = 12;
    public static final int[] SnackbarLayout;
    public static final int SnackbarLayout_android_maxWidth = 0;
    public static final int SnackbarLayout_elevation = 1;
    public static final int SnackbarLayout_maxActionInlineWidth = 2;
    public static final int[] Spinner;
    public static final int Spinner_android_dropDownWidth = 2;
    public static final int Spinner_android_popupBackground = 0;
    public static final int Spinner_android_prompt = 1;
    public static final int Spinner_popupTheme = 3;
    public static final int[] SwitchCompat;
    public static final int SwitchCompat_android_textOff = 1;
    public static final int SwitchCompat_android_textOn = 0;
    public static final int SwitchCompat_android_thumb = 2;
    public static final int SwitchCompat_showText = 9;
    public static final int SwitchCompat_splitTrack = 8;
    public static final int SwitchCompat_switchMinWidth = 6;
    public static final int SwitchCompat_switchPadding = 7;
    public static final int SwitchCompat_switchTextAppearance = 5;
    public static final int SwitchCompat_thumbTextPadding = 4;
    public static final int SwitchCompat_track = 3;
    public static final int[] TabLayout;
    public static final int TabLayout_tabBackground = 3;
    public static final int TabLayout_tabContentStart = 2;
    public static final int TabLayout_tabGravity = 5;
    public static final int TabLayout_tabIndicatorColor = 0;
    public static final int TabLayout_tabIndicatorHeight = 1;
    public static final int TabLayout_tabMaxWidth = 7;
    public static final int TabLayout_tabMinWidth = 6;
    public static final int TabLayout_tabMode = 4;
    public static final int TabLayout_tabPadding = 15;
    public static final int TabLayout_tabPaddingBottom = 14;
    public static final int TabLayout_tabPaddingEnd = 13;
    public static final int TabLayout_tabPaddingStart = 11;
    public static final int TabLayout_tabPaddingTop = 12;
    public static final int TabLayout_tabSelectedTextColor = 10;
    public static final int TabLayout_tabTextAppearance = 8;
    public static final int TabLayout_tabTextColor = 9;
    public static final int[] TextAppearance;
    public static final int TextAppearance_android_shadowColor = 4;
    public static final int TextAppearance_android_shadowDx = 5;
    public static final int TextAppearance_android_shadowDy = 6;
    public static final int TextAppearance_android_shadowRadius = 7;
    public static final int TextAppearance_android_textColor = 3;
    public static final int TextAppearance_android_textSize = 0;
    public static final int TextAppearance_android_textStyle = 2;
    public static final int TextAppearance_android_typeface = 1;
    public static final int TextAppearance_textAllCaps = 8;
    public static final int[] TextInputLayout;
    public static final int TextInputLayout_android_hint = 1;
    public static final int TextInputLayout_android_textColorHint = 0;
    public static final int TextInputLayout_counterEnabled = 5;
    public static final int TextInputLayout_counterMaxLength = 6;
    public static final int TextInputLayout_counterOverflowTextAppearance = 8;
    public static final int TextInputLayout_counterTextAppearance = 7;
    public static final int TextInputLayout_errorEnabled = 3;
    public static final int TextInputLayout_errorTextAppearance = 4;
    public static final int TextInputLayout_hintAnimationEnabled = 9;
    public static final int TextInputLayout_hintTextAppearance = 2;
    public static final int[] Theme;
    public static final int Theme_actionBarDivider = 23;
    public static final int Theme_actionBarItemBackground = 24;
    public static final int Theme_actionBarPopupTheme = 17;
    public static final int Theme_actionBarSize = 22;
    public static final int Theme_actionBarSplitStyle = 19;
    public static final int Theme_actionBarStyle = 18;
    public static final int Theme_actionBarTabBarStyle = 13;
    public static final int Theme_actionBarTabStyle = 12;
    public static final int Theme_actionBarTabTextStyle = 14;
    public static final int Theme_actionBarTheme = 20;
    public static final int Theme_actionBarWidgetTheme = 21;
    public static final int Theme_actionButtonStyle = 49;
    public static final int Theme_actionDropDownStyle = 45;
    public static final int Theme_actionMenuTextAppearance = 25;
    public static final int Theme_actionMenuTextColor = 26;
    public static final int Theme_actionModeBackground = 29;
    public static final int Theme_actionModeCloseButtonStyle = 28;
    public static final int Theme_actionModeCloseDrawable = 31;
    public static final int Theme_actionModeCopyDrawable = 33;
    public static final int Theme_actionModeCutDrawable = 32;
    public static final int Theme_actionModeFindDrawable = 37;
    public static final int Theme_actionModePasteDrawable = 34;
    public static final int Theme_actionModePopupWindowStyle = 39;
    public static final int Theme_actionModeSelectAllDrawable = 35;
    public static final int Theme_actionModeShareDrawable = 36;
    public static final int Theme_actionModeSplitBackground = 30;
    public static final int Theme_actionModeStyle = 27;
    public static final int Theme_actionModeWebSearchDrawable = 38;
    public static final int Theme_actionOverflowButtonStyle = 15;
    public static final int Theme_actionOverflowMenuStyle = 16;
    public static final int Theme_activityChooserViewStyle = 57;
    public static final int Theme_alertDialogButtonGroupStyle = 92;
    public static final int Theme_alertDialogCenterButtons = 93;
    public static final int Theme_alertDialogStyle = 91;
    public static final int Theme_alertDialogTheme = 94;
    public static final int Theme_android_windowAnimationStyle = 1;
    public static final int Theme_android_windowIsFloating = 0;
    public static final int Theme_autoCompleteTextViewStyle = 99;
    public static final int Theme_borderlessButtonStyle = 54;
    public static final int Theme_buttonBarButtonStyle = 51;
    public static final int Theme_buttonBarNegativeButtonStyle = 97;
    public static final int Theme_buttonBarNeutralButtonStyle = 98;
    public static final int Theme_buttonBarPositiveButtonStyle = 96;
    public static final int Theme_buttonBarStyle = 50;
    public static final int Theme_buttonStyle = 100;
    public static final int Theme_buttonStyleSmall = 101;
    public static final int Theme_checkboxStyle = 102;
    public static final int Theme_checkedTextViewStyle = 103;
    public static final int Theme_colorAccent = 84;
    public static final int Theme_colorButtonNormal = 88;
    public static final int Theme_colorControlActivated = 86;
    public static final int Theme_colorControlHighlight = 87;
    public static final int Theme_colorControlNormal = 85;
    public static final int Theme_colorPrimary = 82;
    public static final int Theme_colorPrimaryDark = 83;
    public static final int Theme_colorSwitchThumbNormal = 89;
    public static final int Theme_controlBackground = 90;
    public static final int Theme_dialogPreferredPadding = 43;
    public static final int Theme_dialogTheme = 42;
    public static final int Theme_dividerHorizontal = 56;
    public static final int Theme_dividerVertical = 55;
    public static final int Theme_dropDownListViewStyle = 74;
    public static final int Theme_dropdownListPreferredItemHeight = 46;
    public static final int Theme_editTextBackground = 63;
    public static final int Theme_editTextColor = 62;
    public static final int Theme_editTextStyle = 104;
    public static final int Theme_homeAsUpIndicator = 48;
    public static final int Theme_imageButtonStyle = 64;
    public static final int Theme_listChoiceBackgroundIndicator = 81;
    public static final int Theme_listDividerAlertDialog = 44;
    public static final int Theme_listPopupWindowStyle = 75;
    public static final int Theme_listPreferredItemHeight = 69;
    public static final int Theme_listPreferredItemHeightLarge = 71;
    public static final int Theme_listPreferredItemHeightSmall = 70;
    public static final int Theme_listPreferredItemPaddingLeft = 72;
    public static final int Theme_listPreferredItemPaddingRight = 73;
    public static final int Theme_panelBackground = 78;
    public static final int Theme_panelMenuListTheme = 80;
    public static final int Theme_panelMenuListWidth = 79;
    public static final int Theme_popupMenuStyle = 60;
    public static final int Theme_popupWindowStyle = 61;
    public static final int Theme_radioButtonStyle = 105;
    public static final int Theme_ratingBarStyle = 106;
    public static final int Theme_searchViewStyle = 68;
    public static final int Theme_seekBarStyle = 107;
    public static final int Theme_selectableItemBackground = 52;
    public static final int Theme_selectableItemBackgroundBorderless = 53;
    public static final int Theme_spinnerDropDownItemStyle = 47;
    public static final int Theme_spinnerStyle = 108;
    public static final int Theme_switchStyle = 109;
    public static final int Theme_textAppearanceLargePopupMenu = 40;
    public static final int Theme_textAppearanceListItem = 76;
    public static final int Theme_textAppearanceListItemSmall = 77;
    public static final int Theme_textAppearanceSearchResultSubtitle = 66;
    public static final int Theme_textAppearanceSearchResultTitle = 65;
    public static final int Theme_textAppearanceSmallPopupMenu = 41;
    public static final int Theme_textColorAlertDialogListItem = 95;
    public static final int Theme_textColorSearchUrl = 67;
    public static final int Theme_toolbarNavigationButtonStyle = 59;
    public static final int Theme_toolbarStyle = 58;
    public static final int Theme_windowActionBar = 2;
    public static final int Theme_windowActionBarOverlay = 4;
    public static final int Theme_windowActionModeOverlay = 5;
    public static final int Theme_windowFixedHeightMajor = 9;
    public static final int Theme_windowFixedHeightMinor = 7;
    public static final int Theme_windowFixedWidthMajor = 6;
    public static final int Theme_windowFixedWidthMinor = 8;
    public static final int Theme_windowMinWidthMajor = 10;
    public static final int Theme_windowMinWidthMinor = 11;
    public static final int Theme_windowNoTitle = 3;
    public static final int[] Toolbar;
    public static final int Toolbar_android_gravity = 0;
    public static final int Toolbar_android_minHeight = 1;
    public static final int Toolbar_collapseContentDescription = 19;
    public static final int Toolbar_collapseIcon = 18;
    public static final int Toolbar_contentInsetEnd = 6;
    public static final int Toolbar_contentInsetLeft = 7;
    public static final int Toolbar_contentInsetRight = 8;
    public static final int Toolbar_contentInsetStart = 5;
    public static final int Toolbar_logo = 4;
    public static final int Toolbar_logoDescription = 22;
    public static final int Toolbar_maxButtonHeight = 17;
    public static final int Toolbar_navigationContentDescription = 21;
    public static final int Toolbar_navigationIcon = 20;
    public static final int Toolbar_popupTheme = 9;
    public static final int Toolbar_subtitle = 3;
    public static final int Toolbar_subtitleTextAppearance = 11;
    public static final int Toolbar_subtitleTextColor = 24;
    public static final int Toolbar_title = 2;
    public static final int Toolbar_titleMarginBottom = 16;
    public static final int Toolbar_titleMarginEnd = 14;
    public static final int Toolbar_titleMarginStart = 13;
    public static final int Toolbar_titleMarginTop = 15;
    public static final int Toolbar_titleMargins = 12;
    public static final int Toolbar_titleTextAppearance = 10;
    public static final int Toolbar_titleTextColor = 23;
    public static final int[] View;
    public static final int[] ViewBackgroundHelper;
    public static final int ViewBackgroundHelper_android_background = 0;
    public static final int ViewBackgroundHelper_backgroundTint = 1;
    public static final int ViewBackgroundHelper_backgroundTintMode = 2;
    public static final int[] ViewStubCompat;
    public static final int ViewStubCompat_android_id = 0;
    public static final int ViewStubCompat_android_inflatedId = 2;
    public static final int ViewStubCompat_android_layout = 1;
    public static final int View_android_focusable = 1;
    public static final int View_android_theme = 0;
    public static final int View_paddingEnd = 3;
    public static final int View_paddingStart = 2;
    public static final int View_theme = 4;

    static {
        ActionBar = new int[]{C1117d.height, C1117d.title, C1117d.navigationMode, C1117d.displayOptions, C1117d.subtitle, C1117d.titleTextStyle, C1117d.subtitleTextStyle, C1117d.icon, C1117d.logo, C1117d.divider, C1117d.background, C1117d.backgroundStacked, C1117d.backgroundSplit, C1117d.customNavigationLayout, C1117d.homeLayout, C1117d.progressBarStyle, C1117d.indeterminateProgressStyle, C1117d.progressBarPadding, C1117d.itemPadding, C1117d.hideOnContentScroll, C1117d.contentInsetStart, C1117d.contentInsetEnd, C1117d.contentInsetLeft, C1117d.contentInsetRight, C1117d.elevation, C1117d.popupTheme, C1117d.homeAsUpIndicator};
        int[] iArr = new int[View_android_focusable];
        iArr[View_android_theme] = 16842931;
        ActionBarLayout = iArr;
        iArr = new int[View_android_focusable];
        iArr[View_android_theme] = 16843071;
        ActionMenuItemView = iArr;
        ActionMenuView = new int[View_android_theme];
        ActionMode = new int[]{C1117d.height, C1117d.titleTextStyle, C1117d.subtitleTextStyle, C1117d.background, C1117d.backgroundSplit, C1117d.closeItemLayout};
        ActivityChooserView = new int[]{C1117d.initialActivityCount, C1117d.expandActivityOverflowButtonDrawable};
        AlertDialog = new int[]{16842994, C1117d.buttonPanelSideLayout, C1117d.listLayout, C1117d.multiChoiceItemLayout, C1117d.singleChoiceItemLayout, C1117d.listItemLayout};
        AppBarLayout = new int[]{16842964, C1117d.elevation, C0039c.expanded};
        AppBarLayout_LayoutParams = new int[]{C0039c.layout_scrollFlags, C0039c.layout_scrollInterpolator};
        AppCompatTextView = new int[]{16842804, C1117d.textAllCaps};
        iArr = new int[View_android_focusable];
        iArr[View_android_theme] = C1117d.allowStacking;
        ButtonBarLayout = iArr;
        CollapsingAppBarLayout_LayoutParams = new int[]{C0039c.layout_collapseMode, C0039c.layout_collapseParallaxMultiplier};
        CollapsingToolbarLayout = new int[]{C1117d.title, C0039c.expandedTitleMargin, C0039c.expandedTitleMarginStart, C0039c.expandedTitleMarginTop, C0039c.expandedTitleMarginEnd, C0039c.expandedTitleMarginBottom, C0039c.expandedTitleTextAppearance, C0039c.collapsedTitleTextAppearance, C0039c.contentScrim, C0039c.statusBarScrim, C0039c.toolbarId, C0039c.collapsedTitleGravity, C0039c.expandedTitleGravity, C0039c.titleEnabled};
        CompoundButton = new int[]{16843015, C1117d.buttonTint, C1117d.buttonTintMode};
        CoordinatorLayout = new int[]{C0039c.keylines, C0039c.statusBarBackground};
        CoordinatorLayout_LayoutParams = new int[]{16842931, C0039c.layout_behavior, C0039c.layout_anchor, C0039c.layout_keyline, C0039c.layout_anchorGravity};
        DrawerArrowToggle = new int[]{C1117d.color, C1117d.spinBars, C1117d.drawableSize, C1117d.gapBetweenBars, C1117d.arrowHeadLength, C1117d.arrowShaftLength, C1117d.barLength, C1117d.thickness};
        FloatingActionButton = new int[]{C1117d.elevation, C0039c.rippleColor, C0039c.fabSize, C0039c.pressedTranslationZ, C0039c.borderWidth, C1117d.backgroundTint, C1117d.backgroundTintMode};
        ForegroundLinearLayout = new int[]{16843017, 16843264, C0039c.foregroundInsidePadding};
        LinearLayoutCompat = new int[]{16842927, 16842948, 16843046, 16843047, 16843048, C1117d.divider, C1117d.measureWithLargestChild, C1117d.showDividers, C1117d.dividerPadding};
        LinearLayoutCompat_Layout = new int[]{16842931, 16842996, 16842997, 16843137};
        ListPopupWindow = new int[]{16843436, 16843437};
        MenuGroup = new int[]{16842766, 16842960, 16843156, 16843230, 16843231, 16843232};
        MenuItem = new int[]{16842754, 16842766, 16842960, 16843014, 16843156, 16843230, 16843231, 16843233, 16843234, 16843235, 16843236, 16843237, 16843375, C1117d.showAsAction, C1117d.actionLayout, C1117d.actionViewClass, C1117d.actionProviderClass};
        MenuView = new int[]{16842926, 16843052, 16843053, 16843054, 16843055, 16843056, 16843057, C1117d.preserveIconSpacing};
        NavigationView = new int[]{16842964, 16842973, 16843039, C1117d.elevation, C0039c.menu, C0039c.itemIconTint, C0039c.itemTextColor, C0039c.itemBackground, C0039c.itemTextAppearance, C0039c.headerLayout};
        PopupWindow = new int[]{16843126, C1117d.overlapAnchor};
        iArr = new int[View_android_focusable];
        iArr[View_android_theme] = C1117d.state_above_anchor;
        PopupWindowBackgroundState = iArr;
        RecyclerView = new int[]{16842948, C0039c.layoutManager, C0039c.spanCount, C0039c.reverseLayout, C0039c.stackFromEnd};
        iArr = new int[View_android_focusable];
        iArr[View_android_theme] = C0039c.insetForeground;
        ScrimInsetsFrameLayout = iArr;
        iArr = new int[View_android_focusable];
        iArr[View_android_theme] = C0039c.behavior_overlapTop;
        ScrollingViewBehavior_Params = iArr;
        SearchView = new int[]{16842970, 16843039, 16843296, 16843364, C1117d.layout, C1117d.iconifiedByDefault, C1117d.queryHint, C1117d.defaultQueryHint, C1117d.closeIcon, C1117d.goIcon, C1117d.searchIcon, C1117d.searchHintIcon, C1117d.voiceIcon, C1117d.commitIcon, C1117d.suggestionRowLayout, C1117d.queryBackground, C1117d.submitBackground};
        SnackbarLayout = new int[]{16843039, C1117d.elevation, C0039c.maxActionInlineWidth};
        Spinner = new int[]{16843126, 16843131, 16843362, C1117d.popupTheme};
        SwitchCompat = new int[]{16843044, 16843045, 16843074, C1117d.track, C1117d.thumbTextPadding, C1117d.switchTextAppearance, C1117d.switchMinWidth, C1117d.switchPadding, C1117d.splitTrack, C1117d.showText};
        TabLayout = new int[]{C0039c.tabIndicatorColor, C0039c.tabIndicatorHeight, C0039c.tabContentStart, C0039c.tabBackground, C0039c.tabMode, C0039c.tabGravity, C0039c.tabMinWidth, C0039c.tabMaxWidth, C0039c.tabTextAppearance, C0039c.tabTextColor, C0039c.tabSelectedTextColor, C0039c.tabPaddingStart, C0039c.tabPaddingTop, C0039c.tabPaddingEnd, C0039c.tabPaddingBottom, C0039c.tabPadding};
        TextAppearance = new int[]{16842901, 16842902, 16842903, 16842904, 16843105, 16843106, 16843107, 16843108, C1117d.textAllCaps};
        TextInputLayout = new int[]{16842906, 16843088, C0039c.hintTextAppearance, C0039c.errorEnabled, C0039c.errorTextAppearance, C0039c.counterEnabled, C0039c.counterMaxLength, C0039c.counterTextAppearance, C0039c.counterOverflowTextAppearance, C0039c.hintAnimationEnabled};
        Theme = new int[]{16842839, 16842926, C1117d.windowActionBar, C1117d.windowNoTitle, C1117d.windowActionBarOverlay, C1117d.windowActionModeOverlay, C1117d.windowFixedWidthMajor, C1117d.windowFixedHeightMinor, C1117d.windowFixedWidthMinor, C1117d.windowFixedHeightMajor, C1117d.windowMinWidthMajor, C1117d.windowMinWidthMinor, C1117d.actionBarTabStyle, C1117d.actionBarTabBarStyle, C1117d.actionBarTabTextStyle, C1117d.actionOverflowButtonStyle, C1117d.actionOverflowMenuStyle, C1117d.actionBarPopupTheme, C1117d.actionBarStyle, C1117d.actionBarSplitStyle, C1117d.actionBarTheme, C1117d.actionBarWidgetTheme, C1117d.actionBarSize, C1117d.actionBarDivider, C1117d.actionBarItemBackground, C1117d.actionMenuTextAppearance, C1117d.actionMenuTextColor, C1117d.actionModeStyle, C1117d.actionModeCloseButtonStyle, C1117d.actionModeBackground, C1117d.actionModeSplitBackground, C1117d.actionModeCloseDrawable, C1117d.actionModeCutDrawable, C1117d.actionModeCopyDrawable, C1117d.actionModePasteDrawable, C1117d.actionModeSelectAllDrawable, C1117d.actionModeShareDrawable, C1117d.actionModeFindDrawable, C1117d.actionModeWebSearchDrawable, C1117d.actionModePopupWindowStyle, C1117d.textAppearanceLargePopupMenu, C1117d.textAppearanceSmallPopupMenu, C1117d.dialogTheme, C1117d.dialogPreferredPadding, C1117d.listDividerAlertDialog, C1117d.actionDropDownStyle, C1117d.dropdownListPreferredItemHeight, C1117d.spinnerDropDownItemStyle, C1117d.homeAsUpIndicator, C1117d.actionButtonStyle, C1117d.buttonBarStyle, C1117d.buttonBarButtonStyle, C1117d.selectableItemBackground, C1117d.selectableItemBackgroundBorderless, C1117d.borderlessButtonStyle, C1117d.dividerVertical, C1117d.dividerHorizontal, C1117d.activityChooserViewStyle, C1117d.toolbarStyle, C1117d.toolbarNavigationButtonStyle, C1117d.popupMenuStyle, C1117d.popupWindowStyle, C1117d.editTextColor, C1117d.editTextBackground, C1117d.imageButtonStyle, C1117d.textAppearanceSearchResultTitle, C1117d.textAppearanceSearchResultSubtitle, C1117d.textColorSearchUrl, C1117d.searchViewStyle, C1117d.listPreferredItemHeight, C1117d.listPreferredItemHeightSmall, C1117d.listPreferredItemHeightLarge, C1117d.listPreferredItemPaddingLeft, C1117d.listPreferredItemPaddingRight, C1117d.dropDownListViewStyle, C1117d.listPopupWindowStyle, C1117d.textAppearanceListItem, C1117d.textAppearanceListItemSmall, C1117d.panelBackground, C1117d.panelMenuListWidth, C1117d.panelMenuListTheme, C1117d.listChoiceBackgroundIndicator, C1117d.colorPrimary, C1117d.colorPrimaryDark, C1117d.colorAccent, C1117d.colorControlNormal, C1117d.colorControlActivated, C1117d.colorControlHighlight, C1117d.colorButtonNormal, C1117d.colorSwitchThumbNormal, C1117d.controlBackground, C1117d.alertDialogStyle, C1117d.alertDialogButtonGroupStyle, C1117d.alertDialogCenterButtons, C1117d.alertDialogTheme, C1117d.textColorAlertDialogListItem, C1117d.buttonBarPositiveButtonStyle, C1117d.buttonBarNegativeButtonStyle, C1117d.buttonBarNeutralButtonStyle, C1117d.autoCompleteTextViewStyle, C1117d.buttonStyle, C1117d.buttonStyleSmall, C1117d.checkboxStyle, C1117d.checkedTextViewStyle, C1117d.editTextStyle, C1117d.radioButtonStyle, C1117d.ratingBarStyle, C1117d.seekBarStyle, C1117d.spinnerStyle, C1117d.switchStyle, C1117d.RoundAvatarImageViewStyle};
        Toolbar = new int[]{16842927, 16843072, C1117d.title, C1117d.subtitle, C1117d.logo, C1117d.contentInsetStart, C1117d.contentInsetEnd, C1117d.contentInsetLeft, C1117d.contentInsetRight, C1117d.popupTheme, C1117d.titleTextAppearance, C1117d.subtitleTextAppearance, C1117d.titleMargins, C1117d.titleMarginStart, C1117d.titleMarginEnd, C1117d.titleMarginTop, C1117d.titleMarginBottom, C1117d.maxButtonHeight, C1117d.collapseIcon, C1117d.collapseContentDescription, C1117d.navigationIcon, C1117d.navigationContentDescription, C1117d.logoDescription, C1117d.titleTextColor, C1117d.subtitleTextColor};
        View = new int[]{16842752, 16842970, C1117d.paddingStart, C1117d.paddingEnd, C1117d.theme};
        ViewBackgroundHelper = new int[]{16842964, C1117d.backgroundTint, C1117d.backgroundTintMode};
        ViewStubCompat = new int[]{16842960, 16842994, 16842995};
    }
}
